FROM ludwigai/ludwig:latest

ENV HOME /home/neocortex/

WORKDIR ${HOME}

COPY ./core ./core

RUN apt-get update -y &&\
    apt-get install libpq-dev python-dev -y

RUN pip install --no-cache-dir --upgrade pip && \
    pip install psycopg2 
