FROM docker

ENV HOME /home/node/backend

WORKDIR ${HOME}

COPY . .
RUN apk add --no-cache --update nodejs npm
RUN apk add --update docker openrc
RUN rc-update add docker boot
RUN npm install
RUN npm run build

