version: '3.8'
services:
  postgresql-airbus-db:
    image: postgis/postgis
    container_name: postgresql-airbus
    restart: always
    networks:
      - airbus-network
    volumes:
      -  airbus-db-data:/var/lib/postgresql/data
    env_file:
      - .development.env
    ports:
      - 5432:5432
volumes:
 airbus-db-data:
networks:
   airbus-network:
    driver: bridge
